# Build XDC in a stock Go builder container
FROM golang:1.12-alpine as builder

RUN apk add --no-cache make gcc musl-dev linux-headers git

ADD . /XDCchain
RUN cd /XDCchain && make all

# Pull all binaries into a second stage deploy alpine container
FROM alpine:latest

LABEL maintainer="anil@xinfin.org"

WORKDIR /XDCchain

RUN apk add --no-cache ca-certificates
COPY --from=builder /XDCchain/build/bin/* /usr/local/bin/

RUN chmod +x /usr/local/bin/*

EXPOSE 8545
EXPOSE 30303

CMD ["--help"]