ec2_rpcs:
  hosts:
    devnet:
      ansible_host: #TODO: update
      ansible_port: 22
      ansible_user: ec2-user
      deploy_path: /work/XinFin-Node/devnet
    testnet:
      ansible_host: #TODO: update
      ansible_port: 22
      ansible_user: ec2-user
      deploy_path: /work/XinFin-Node/testnet
    mainnet:
      ansible_host: #TODO: update
      ansible_port: 22
      ansible_user: ec2-user
      deploy_path: /work/XinFin-Node/mainnet