---
- name: Run Bash Script on Host
  hosts: "{{ network }}"
  become: true  #sudo/root

  tasks:
    - name: Update RPC image version
        # export RPC_IMAGE={{ rpc_image }}
      shell: |
        export RPC_IMAGE=xinfinorg/devnet:dev-upgrade-stable-5024107
        cd {{ deploy_path }}
        git pull
        ./docker-down.sh
        ./docker-up-hash.sh
        docker ps
      register: output
    - debug: var=output.stdout_lines