name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  devnet_build_push:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.out.outputs.image_name }}
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push Docker images
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          image_name=xinfinorg/devnet:dev-upgrade-${git_hash}
          # docker build -t xinfinorg/devnet:latest -f cicd/Dockerfile .
          # docker tag xinfinorg/devnet:latest $image_name
          # docker push $image_name

      - name: Output image name
        id: out
        run:
          echo $image_name 
          echo "image_name=$image_name" >> "$GITHUB_OUTPUT"


      - name: show output
        run: |
          echo ${{ steps.out.outputs.image_name }}

  rpcnode_terraform_apply:
    runs-on: ubuntu-latest
    needs: devnet_build_push
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: check image
        run:
          echo ${{ needs.devnet_build_push.outputs.image_name }}
          echo asdf
      # - name: Update RPC nodes image
      #   uses: dawidd6/action-ansible-playbook@v2
      #   with:
      #     playbook: playbooks/update-image.yaml
      #     directory: ./cicd/ansible
      #     key: ${{secrets.SSH_PRIVATE_KEY_DEVNET}}
      #     options: |
      #       --inventory inventory.yaml
      #       --extra-vars network=ec2_rpcs
      #       --extra-vars rpc_image=${{ needs.devnet_build_push.outputs.image_name }}

