name: CI

on:
  push:
    branches:
      - 'ec2-test-2'

env:
  tf_version: "1.3.0"
  tf_init_cli_options: "-input=false"
  tf_validation_cli_options: ""
  tf_plan_cli_options: "-lock=false -input=false"
  tf_apply_cli_options: "-auto-approve -input=false"

jobs:
  rpcnode_terraform_apply:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Apply
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          cd cicd/terraform
          cat main.tf
          cat module/ec2_rpc/main.tf
          terraform init ${{ env.tf_init_cli_options }}
          terraform apply ${{ env.tf_apply_cli_options }}

  # update-image:
  #   needs: rpcnode_terraform_apply
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out code
  #       uses: actions/checkout@v4

  #     - name: Update RPC nodes image
  #       uses: dawidd6/action-ansible-playbook@v2
  #       with:
  #         playbook: playbooks/update-image.yaml
  #         directory: ./cicd/ansible
  #         key: ${{secrets.SSH_PRIVATE_KEY_DEVNET}}
  #         options: |
  #           --inventory inventory.yaml
  #           --extra-vars rpc_image=xinfinorg/devnet:dev-upgrade-${git_hash}
